steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'Dockerfile.prod',
        '-t',
        'asia-southeast1-a-docker.pkg.dev/social-network-api-424501/custom-fastapi/custom-fastapi:latest',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-a-docker.pkg.dev/social-network-api-424501/custom-fastapi/custom-fastapi:latest']
