name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    # defaults:
    #   run:
    #     working-directory: ./Social_Network_API

    steps:
      - uses: actions/checkout@v3
      - name: 'Create env file'
        run: echo "${{ secrets.SOCIAL_NETWORK_API_ENV }}" > .env.development
      - name: Build the Docker image
        run: docker build --progress=plain -t khacvu0505/social-network-api:v2 -f Dockerfile.dev .
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Docker image to Docker Hub
        run: docker push khacvu0505/social-network-api:v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull khacvu0505/social-network-api:v2
            docker stop social-network-api
            docker social-network-api
            docker run -dp 3000:4000 --name social-network-api --restart unless-stopped -v ~/social-network-api/uploads:/app/public/uploads khacvu0505/social-network-api:v2
